### ISSUE TITLE
Rename a project

### ISSUE THREAD

**Issue by Roberciiik** [11jo/Icewind_EET#3]
Hello,
Could you rename this project to "IWD_EET_End" or simply to "IWD_End" to follow the EET_End convention?

I found it hard to search for and navigate inside the folder when both IWD projects are named: IWD1_EET and IWD2_EET, and the last one is Icewind_EET. Just a quality of life suggestion.

Thanks!

**Comment by 11jo** [comment]
I agree, it's a good idea !

I've sent Tipun a message asking for his thoughts on this matter, if he approves I'll make the change.

**Comment by 11jo** [comment]
Hello @Roberciiik !

Tipun follow your idea and here is a brand new [iwd_eet_end](https://github.com/The-Gate-Project/IWD_EET_End).

**Comment by Roberciiik** [comment]
That's lovely! Thank you for the support! 💪
